export enum OrderEventType {
  ORDER_MAINDATA_UPDATED = 'ORDER_MAINDATA_UPDATED',
  ORDER_DELETED = 'ORDER_DELETED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ORDER_GROUP_ADDED = 'ORDER_GROUP_ADDED',
  ORDER_GROUP_UPDATED = 'ORDER_GROUP_UPDATED',
  ORDER_GROUP_DELETED = 'ORDER_GROUP_DELETED'
}